#主配置文件，配置的公共的配置
#server
server:
  port: 8083
#  spring
spring:
  application:
    name: demo
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
#配置过滤
  profiles:
    active: dev #激活哪一个，声明后会将dev和主配置一起加载，类似java的解耦思想 开关
#datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    validation-query: select 'x'
    test-while-idle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: com/example/demo/bussiness/mapper/**.xml
  type-aliases-package: com.example.demo.**.entity






