#主配置文件，配置的公共的配置
#server
server:
  port: 8083
#  spring
spring:
  application:
    name: demo
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
#配置过滤
  profiles:
    active: dev #激活哪一个，声明后会将dev和主配置一起加载，类似java的解耦思想 开关
#datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    validation-query: select 'x'
    test-while-idle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: com/example/demo/bussiness/mapper/**.xml
  type-aliases-package: com.example.demo.**.entity

  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
      # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    in-memory: true
      # 等待消息发送响应的时间。设置为0等待永远。
    send-timeout: 0
      # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    non-blocking-redelivery: false
      # 是否用Pooledconnectionfactory代替普通的ConnectionFactory
    pool:
      enabled: true
    packages:
      trust-all: true   # 如果使用ObjectMessage传输对象，必须要加上这个信任包，否则会报ClassNotFound异常
  jms:
      #默认情况下activemq提供的是queue模式，若要使用topic模式需要配置下面配置
    pub-sub-domain: true

aaa:
  aa: 1
  cc: 2





